### ISSUE TITLE
przeciwnicy

### ISSUE THREAD

**Issue by Flashrow** [Flashrow/CyberPunk2020#5]
przeciwnicy, którzy mogą biegać, strzelać, namierzać playera

na razie nie muszą być zbyt inteligentni

**Comment by skrzypak** [comment]
NPC: Humanoid,  Enemy, Questy
Humanoid - tzw. ameby
Enemy - proste namierzanie i szczelanie w gracza + aktualizacja paska HP gracza i NPC'ta
Quest - gotowy podkład pod zrobienie interakcji (przycisk F, zmiana kamery)
Movment: poruszanie się do losowo wskazanych punktów + detekcja gracza i reagowanie na niego
Każdy NPC dzieli się na dwie kategorie: 
- movable -  mogą się przemieszczać np. kosmici (muszą mieć Nav Mesh Agent i NPCMovment.cs)
- static - pozostają w miejscu i odwracają się w strone gracza np. wieżyczki
